### ISSUE TITLE
KC6: Getting feedback on the VDS service

### ISSUE THREAD

**Issue by davissn30** [dcppc/2018-august-workshop#6]
breakout topic 
@RebeccaBoyles 
This was discussed at the most recent KC6 call.

**Comment by webermn** [comment]
May be related to #8 ?

**Comment by RebeccaBoyles** [comment]
@rspahnn @raynamharris My understanding of this session is that it will be a chance to provide very specific technical feedback and ideas for future development to the VDS development team.
@kevinwilson Agree?

**Comment by kevinwilson** [comment]
It think it is that, but also how a range of different things fit into the big picture: VDS, SDDP, WhiteList, Commons Google accounts, etc.

**Comment by raynamharris** [comment]
Closing this in favor of #8 All things auth.
